version: '2'

services:

  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./code:/app
      - ./logs:/logs 

  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./nginx/conf/myapp.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf

networks:
    app-tier:
        driver: bridge